[build-system]
requires = ["setuptools", "wheel", "scikit-build", "cmake", "Cython"]
build-backend = "setuptools.build_meta"

[project]
name = "your-package-name"
version = "0.1.0"
description = "A short description of your package"
authors = [
    { name = "Your Name", email = "your@email.com" },
]
license = { text = "MIT License" }
